### ISSUE TITLE
看了您的代码。有点疑惑啊

### ISSUE THREAD

**Issue by WinKingFace** [staugur/Flask-PluginKit#1]
插件中 蓝图已经具备钩子功能。但是在目前的代码逻辑上，你把插件的钩子给注册成全局的了
，导致 项目启动的时候 所有注册的钩子都会使用

**Comment by WinKingFace** [comment]
flask 二次封装了，感觉也没有想要的意思啊？

**Comment by staugur** [comment]
是的，钩子就是我之前旧版本的三种，放到全局了，蓝图也有自己的钩子，只是目前懒得加上。
二次封装？是说那个加的before_request_top、before_request_second两个装饰器吧，这也是旧版本的，当时个人有要求所以才加的，重构也就顺便保留了。

**Comment by WinKingFace** [comment]
膜拜大佬写的代码，

**Comment by staugur** [comment]
啊咧咧
