### ISSUE TITLE
Flask-PluginKit 结合flask-classful

### ISSUE THREAD

**Issue by WheatMaThink** [staugur/Flask-PluginKit#2]
Flask-PluginKit 非常好用，正在测试验证中，对程序结构来说非常方便。

在使用过程中，发现了flask-classful ，作者可以考虑一下两者的结合。（业务逻辑比blueprint, Viewfunc 方便很多）
https://github.com/teracyhq/flask-classful

 "vepclass": self._vepclass_handler,

 for vep in self.get_enabled_vepClass:
            classview = vep.pop("classview")
            # objlist = dir(classview)
            classview.register(app=app, **vep)

**Comment by staugur** [comment]
Get！
我先看下

-----
Add in v3.5.0
