### ISSUE TITLE
semver 3.0 renamed isvaldi()

### ISSUE THREAD

**Issue by pc-coholic** [staugur/Flask-PluginKit#5]
semver recently released version 3.0 which changed `Version().isvalid()` to `is_valid()`: https://github.com/python-semver/python-semver/blob/92276867422b70bbb67fdd258eed7dd3f5888237/src/semver/version.py#L684-L696

We should probably either pin semver to 2.* or change the function call too and pin semver to 3.*

**Comment by staugur** [comment]
Thanks. I'll fix it tomorrow.
